// Generated by gencpp from file odom_module/clear_imuResponse.msg
// DO NOT EDIT!


#ifndef ODOM_MODULE_MESSAGE_CLEAR_IMURESPONSE_H
#define ODOM_MODULE_MESSAGE_CLEAR_IMURESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace odom_module
{
template <class ContainerAllocator>
struct clear_imuResponse_
{
  typedef clear_imuResponse_<ContainerAllocator> Type;

  clear_imuResponse_()
    : is_success(0)  {
    }
  clear_imuResponse_(const ContainerAllocator& _alloc)
    : is_success(0)  {
  (void)_alloc;
    }



   typedef int8_t _is_success_type;
  _is_success_type is_success;





  typedef boost::shared_ptr< ::odom_module::clear_imuResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::odom_module::clear_imuResponse_<ContainerAllocator> const> ConstPtr;

}; // struct clear_imuResponse_

typedef ::odom_module::clear_imuResponse_<std::allocator<void> > clear_imuResponse;

typedef boost::shared_ptr< ::odom_module::clear_imuResponse > clear_imuResponsePtr;
typedef boost::shared_ptr< ::odom_module::clear_imuResponse const> clear_imuResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::odom_module::clear_imuResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::odom_module::clear_imuResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::odom_module::clear_imuResponse_<ContainerAllocator1> & lhs, const ::odom_module::clear_imuResponse_<ContainerAllocator2> & rhs)
{
  return lhs.is_success == rhs.is_success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::odom_module::clear_imuResponse_<ContainerAllocator1> & lhs, const ::odom_module::clear_imuResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace odom_module

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::odom_module::clear_imuResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::odom_module::clear_imuResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::odom_module::clear_imuResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::odom_module::clear_imuResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::odom_module::clear_imuResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::odom_module::clear_imuResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::odom_module::clear_imuResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "89b0a853bbde8d612a2b45f225ec733d";
  }

  static const char* value(const ::odom_module::clear_imuResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x89b0a853bbde8d61ULL;
  static const uint64_t static_value2 = 0x2a2b45f225ec733dULL;
};

template<class ContainerAllocator>
struct DataType< ::odom_module::clear_imuResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "odom_module/clear_imuResponse";
  }

  static const char* value(const ::odom_module::clear_imuResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::odom_module::clear_imuResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 is_success\n"
"\n"
;
  }

  static const char* value(const ::odom_module::clear_imuResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::odom_module::clear_imuResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.is_success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct clear_imuResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::odom_module::clear_imuResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::odom_module::clear_imuResponse_<ContainerAllocator>& v)
  {
    s << indent << "is_success: ";
    Printer<int8_t>::stream(s, indent + "  ", v.is_success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ODOM_MODULE_MESSAGE_CLEAR_IMURESPONSE_H
